### PR TITLE
Manual request form data added. 

### PR DESCRIPTION
**Pull request by geramirez**
This PR adds the request form data collected from [issue 234](https://github.com/18F/foia-hub/issues/234).

I've assigned this PR to myself while I validate the data and make sure it works with foia-hub.

### CODE REVIEW

**Comment by geramirez** [comment]
Just tested the updates with foia-hub, everything seems to be in order. 

Also, the [NHTSA direct form link](http://www.nhtsa.gov/nhtsa-dpmextn/jsp/email/email_nhtsa_foia.jsp) don't have much context so I used [this URL](http://www.nhtsa.gov/FOIA) instead. It's a little difficult to find the form, but it provides more context. Thoughts?

Otherwise, this PR is ready to be merged.

**Comment by rjmajma** [comment]
:+1: on the NHTSA form.

**Comment by jackiekazil** [comment]
@ramirezg it looks like there are some conflicts in this data w/ master. Can you merge master in this PR OR rebase master to resolve?

**Comment by konklone** [comment]
I just fixed the merge conflicts (I'd started this earlier today, and forgot to assign myself to the PR).

**Comment by konklone** [comment]
...and there are a few more conflicts since I last did a pull. Fixing those now.

**Comment by konklone** [comment]
OK, done!

**Pull request merged**
