### PR TITLE
address organizer added to scraper and tests

### PR DESCRIPTION
**Pull request by geramirez**
formatting addresses

### CODE REVIEW

**Comment by konklone** [comment]
Nice!

**Comment by geramirez** [comment]
@konklone  wait, this wasn't done. I still need to update the actual yamls and layer_with_csv.py

**Comment by konklone** [comment]
Rrrg, I moved too fast - sorry.

**Comment by rjmajma** [comment]
Hey @konklone, breaking your own rules? We should wait till @ramirezg unassigns himself from it.

**Comment by konklone** [comment]
Yes - that was my bad, I didn't review it with enough care.

**Pull request merged**
