### PR TITLE
Fixing differences between the manual and auto data

### PR DESCRIPTION
**Pull request by geramirez**
1. Created a script for picking out differences. We might want to add this to the tests.  
2. Started the processing of correcting data.

### CODE REVIEW

**Comment by konklone** [comment]
Nice. I will wait for you to note that it's ready for review, but this is clutch work.

**Comment by khandelwal** [comment]
So, I don't exactly remember how the manual data was created. But I'm having a hard time believing that these inconsistencies crept in. How did that happen? 

I didn't type out the manual data by hand. So, where are these new names coming from.

**Comment by khandelwal** [comment]
@konklone mentioned somewhere else that 'didn't type out the manual data by hand' is a weird sentence. What I mean by that is, especially with agency/office names - those where copy, pasted from the generated YAML files. Except for typos that crept in, there really shouldn't be differences.

**Comment by geramirez** [comment]
Maybe the new tests are a overkill, if so I can always keep the manual data validation tests as a separate python script.

**Comment by khandelwal** [comment]
You still need to answer my question above. ^ 
Why are there so many changes? Can you dig into the history of what happened?

**Comment by geramirez** [comment]
All the inconsistencies were manual. 

Looks there were names in `typo.py` that were carried through to the manual data files. 
git log --follow -p manual_data/DoD.yaml

```
commit 0e928b6ac2a24511d039fc4731074034cbad2184
Author: Shashank Khandelwal <shashank.khandelwal@gsa.gov>
Date:   Thu Oct 23 19:42:51 2014 +0000

    Pull data from typos.py into YAML files

diff --git a/contacts/manual_data/DoD.yaml b/contacts/manual_data/DoD.yaml
new file mode 100644
index 0000000..ebfcae2
--- /dev/null
+++ b/contacts/manual_data/DoD.yaml
@@ -0,0 +1,19 @@
+departments:
+- name: Office of the Secretary and Joint Staff
+  top_level: true
+- name: Department of the Air Force
+  top_level: true
+- name: Department of the Army
+  top_level: true
+- name: Department of the Navy
+  top_level: true
+- name: Marine Corps
+  top_level: true
+- name: National Geographic Intelligence Agency
+  top_level: true
+- name: National Guard Bureau
+  top_level: true
+- name: National Reconnaissance Office
+  top_level: true
+- name: National Security Agency
+  top_level: true
```

git log --follow -p typos.py

```
commit 04fb16c4053648e2819a71f6d99c5b597fe79af6
Author: CM Lubinski <christopher.lubinski@gsa.gov>
Date:   Wed Sep 24 22:26:18 2014 +0000

    Scraper can be configured with keywords, top_level flag

diff --git a/contacts/typos.py b/contacts/typos.py
index c409f83..afa7ad9 100644
--- a/contacts/typos.py
+++ b/contacts/typos.py
@@ -4,3 +4,76 @@
 REPLACEMENTS = {
     "(256) 544-007 ": "(256) 544-0007 "
 }
+
+
+KEYWORDS = {
+    'CIA': ['spies', 'espionage', 'counterintelligence'],
+    'GSA': ['purchase cards', 'federal contracts', 'government forms'],
+    'OSTP': ['white house', 'cto'],
+}
+
+
+#   Clearly not an elegant solution -- spell out all
+#   departments/offices/components which should get the top_level flag
+TOP_LEVEL = {
+    'DHS': [
+        'U.S. Citizenship & Immigration Services', 'U.S. Coast Guard',
+        'U.S. Customs & Border Protection',
+        'Federal Emergency Management Agency',
+        'Federal Law Enforcement Training Center',
+        'U.S. Immigration & Customs Enforcement',
+        'United States Secret Service'],
+    'DOC': [
+        'Census Bureau', 'International Trade Administration',
+        'Minority Business Development Agency',
+        'National Institute of Standards and Technology',
+        'National Technical Information Service',
+        'National Oceanic and Atmospheric Administration',
+        'U.S. Patent and Trademark Office'],
+    'DoD': [
+        'Office of the Secretary and Joint Staff',
+        'Department of the Air Force', 'Department of the Army',
+        'Department of the Navy', 'Marine Corps',
+        'National Geographic Intelligence Agency', 'National Guard Bureau',
+        'National Reconnaissance Office', 'National Security Agency'],
+    'DOE': ['Office of Scientific and Technical Information'],
+    'DOI': [
+        'Bureau of Indian Affairs', 'Bureau of Land Management',
+        'Bureau of Ocean Energy Management', 'Bureau of Reclamation',
+        'Bureau of Safety and Environmental Enforcement',
+        'U.S. Fish and Wildlife Service', 'National Park Service'],
+    'DOJ': [
+        'Office of the Attorney General',
+        'Bureau of Alcohol, Tobacco, Firearms, and Explosives',
+        'Drug Enforcement Administration', 'Federal Bureau of Investigation',
+        'Federal Bureau of Prisons',
+        'Office of Community Oriented Policing Services',
+        'United States Marshals Service'],
+    'DOT': [
+        'Federal Aviation Administration',
+        'National Highway Traffic Safety Administration'],
+    'HHS': [
+        'Administration for Community Living',
+        'Agency for Healthcare Research and Quality',
+        'Centers for Disease Control and Prevention',
+        'Center for Medicare and Medicaid Services',
+        'Food and Drug Administration',
+        'Health Resources and Services Administration',
+        'Indian Health Service', 'National Institutes of Health',
+        'Substance Abuse and Mental Health Services Administration'],
+    'NASA': ['Jet Propulsion Laboratory', 'NASA Shared Services Center'],
+    'Treasury': [
+        'Alcohol and Tobacco Tax and Trade Bureau',
+        'Bureau of Engraving and Printing',
+        'Comptroller of the Currency',
+        'Financial Crimes Enforcement Network',
+        'Internal Revenue Service',
+        'United States Mint'],
+    'U.S. DOL': [
+        'Bureau of International Labor Affairs', 'Bureau of Labor Statistics',
+        'Employee Benefits Security Administration',
+        'Employment & Training Administration', 'Job Corps',
+        'Mine Safety & Health Administration',
+        'Occupational Safety & Health Administration'],
+    'USPS': ['Postal Inspection Service'],
+}
```

The other changes were redundancies. Like agency names on the department-level.

**Pull request merged**
